[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 14.0

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding.x = 10
padding.y = 10

[colors.primary]
background = "0x002b36"
foreground = "0x93a1a1"

[colors.normal]
black   = "0x002b36"
red     = "0xdc322f"
green   = "0x859900"
yellow  = "0xb58900"
blue    = "0x268bd2"
magenta = "0x6c71c4"
cyan    = "0x2aa198"
white   = "0x93a1a1"

[colors.bright]
black   = "0x657b83"
red     = "0xdc322f"
green   = "0x859900"
yellow  = "0xb58900"
blue    = "0x268bd2"
magenta = "0x6c71c4"
cyan    = "0x2aa198"
white   = "0xfdf6e3"
